#语言选项（支持 zh_cn,en_us）
language: zh_cn
#是否使用客户端语言（仅在Fabric生效）
client-language: false
#是否开启自动更新
automatic-updates: false
#是否接入在线网站(统计信息会被上传，详情见 https://w.csk.asia/toneko)
online: true









































































































#下面没内容了















































































#下面没内容了

















































#下面没内容了





































#我是胡桃的狗!!!!






































#下面没内容了




































































#下面没内容了


























































#下面没内容了




















































#欢迎加群836602883