#语言选项（支持 zh_cn,en_us）
language: zh_cn
#是否使用客户端语言（仅在Fabric生效）
client-language: false
#是否开启自动更新
automatic-updates: false
#Ai功能
AI:
  # 是否启用AI
  enable: false
  #AI的API,占位符 %text% = 用户输入, %prompt% = 提示词
  API: "https://chat.ai.crystalneko.online?t=%text%&&p=%prompt%"
  #提示词，占位符 %name% = 猫娘名称, %owner% = 主人
  prompt: "你是一只可爱的猫娘，你的名字是%name%，你的主人是%owner%"













































































#下面没内容了














































#下面没内容了
















































#下面没内容了



































# 猫羽雫好可爱啊














































#据说"1"+"1"="11"哦





























# 诶嘿，被发现了ლ(╹◡╹ლ)