name: toNeko
version: '${project.version}'
main: com.crystalneko.toneko.ToNeko
api-version: '1.20'
commands:
  toneko:
    usage: /toneko help
    aliases: [cnk,tocat]
permissions:
  toneko.command:
    default: true
  toneko.command.item:
    default: true
  toneko.command.remove:
      default: true